name: CI and CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm test

  deploy:
    if: success()  
    runs-on: ubuntu-latest
    needs: [test]
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_github_actions
          chmod 600 ~/.ssh/id_github_actions
          ssh-keyscan -H 46.249.100.7 >> ~/.ssh/known_hosts

      - name: Create deployment folder
        run: ssh -i ~/.ssh/id_github_actions root@46.249.100.7 "mkdir -p ci-cd-demo"
      
      - name: Copy app folder
        run: scp -i ~/.ssh/id_github_actions -r . root@46.249.100.7:ci-cd-demo/

      - name: deploy
        run: |
          ssh -i ~/.ssh/id_github_actions root@46.249.100.7 <<EOF
          cd ci-cd-demo
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up --build -d
          EOF