name: CI and CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm test

  deploy:
    name: Deploy Backend
    runs-on: self-hosted
    needs: [test]
    steps: 
      
      - name: Create deployment folder
        run: ssh root@46.249.100.7 "mkdir -p ci-cd-demo"
      
      - name: Copy docker-compose file
        run: scp -oStrictHostKeyChecking=no docker-compose.yml root@46.249.100.7:ci-cd-demo/docker-compose.yml

      - name: Set ENV variable and deploy
        run: |
          ssh root@46.249.100.7 <<EOF
          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd-demo
          docker compose -f docker-compose.yml pull -q
          docker compose -f docker-compose.yml up -d
          EOF


